// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BtGeneratePairingCode() {
  return window['go']['main']['App']['BtGeneratePairingCode']();
}

export function BtGetConfig() {
  return window['go']['main']['App']['BtGetConfig']();
}

export function BtGetStatus() {
  return window['go']['main']['App']['BtGetStatus']();
}

export function BtJoinByCode(arg1) {
  return window['go']['main']['App']['BtJoinByCode'](arg1);
}

export function BtSaveConfig(arg1) {
  return window['go']['main']['App']['BtSaveConfig'](arg1);
}

export function BtStart() {
  return window['go']['main']['App']['BtStart']();
}

export function BtStop() {
  return window['go']['main']['App']['BtStop']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ImportFromDir(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ImportFromDir'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListScenes() {
  return window['go']['main']['App']['ListScenes']();
}

export function ListScenesFor(arg1) {
  return window['go']['main']['App']['ListScenesFor'](arg1);
}

export function MidiCurrentDevice() {
  return window['go']['main']['App']['MidiCurrentDevice']();
}

export function MidiGetConfig() {
  return window['go']['main']['App']['MidiGetConfig']();
}

export function MidiIsRunning() {
  return window['go']['main']['App']['MidiIsRunning']();
}

export function MidiListDevices() {
  return window['go']['main']['App']['MidiListDevices']();
}

export function MidiSaveConfig(arg1) {
  return window['go']['main']['App']['MidiSaveConfig'](arg1);
}

export function MidiStart() {
  return window['go']['main']['App']['MidiStart']();
}

export function MidiStop() {
  return window['go']['main']['App']['MidiStop']();
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestConnections() {
  return window['go']['main']['App']['TestConnections']();
}

export function TriggerScene(arg1) {
  return window['go']['main']['App']['TriggerScene'](arg1);
}
