// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function ImportFromDir(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListScenes():Promise<Array<string>>;

export function ListScenesFor(arg1:string):Promise<Array<string>>;

export function MidiGetConfig():Promise<config.MidiConfig>;

export function MidiListDevices():Promise<Array<string>>;

export function MidiSaveConfig(arg1:config.MidiConfig):Promise<void>;

export function MidiStart():Promise<void>;

export function MidiStop():Promise<void>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function TestConnections():Promise<Record<string, string>>;

export function TriggerScene(arg1:string):Promise<void>;
